#####################################
# 具体配置 可以参考
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#####################################
# banner
banner:
  charset: UTF-8
  location: classpath:banner.txt

# 应用属性配置
application:
  name: schedule-job
  version: v1.0.0

# 服务端配置
server:
  port: ${port:54321}
  contextPath: /
  compression:
    enabled: true

# WARNING: `spring.config.name` and `spring.config.location` are used very early to
# determine which files have to be loaded so they have to be defined as an environment
# property (typically OS env, system property or command line argument).
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    converters:
      preferred-json-mapper: true
  mvc:
    favicon:
      enabled: false

# multipart 配置
multipart:
  enabled: true
  file-size-threshold: 0
  location: /
  max-file-size: 1Mb
  max-request-size: 10Mb

# MyBatis
mybatis:
  mapperLocations: classpath:/mapper/**/*Mapper.xml
  configLocation: classpath:mybatis-config.xml

# logback config
# You cannot use extensions in the standard logback.xml configuration file since it’s loaded too early.
# You need to either use logback-spring.xml or define a logging.config property.
# path不以'/'开头时，默认是从此类所在的包下取资源；
# path以'/'开头时，则是从项目的ClassPath根下获取资源。在这里'/'表示ClassPath
# Class.getResource和ClassLoader.getResource的区别
logging:
  config: classpath:config/logback.xml

# 配置文件名称，内部加载使用
config:
  quartz-file-name: quartz.properties
  redis-file-name: redis.yml
  db-file-name: datasource.yml


###################################
# 缺省数据库地址 dev
###################################
dbServer:
  default: 10.33.107.30:6606
  read: 10.33.107.30:6606
  write: 10.33.107.30:6606
datasource:
  default:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: default
    continue-on-error: false
    jdbc-url: jdbc:mysql://${dbServer.default}/schedule_job?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
    username: test
    password: 123456
    connection-timeout: 30000
    connection-test-query: SELECT 1
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 600000
    destroy-method: shutdown
    auto-commit: false
  read:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: read
    continue-on-error: false
    jdbc-url: jdbc:mysql://${dbServer.read}/schedule_job?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
    username: test
    password: 123456
    connection-timeout: 30000
    connection-test-query: SELECT 1
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 600000
    destroy-method: shutdown
    auto-commit: false
  write:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: write
    continue-on-error: false
    jdbc-url: jdbc:mysql://${dbServer.write}/schedule_job?useSSL=true&verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8
    username: test
    password: 123456
    connection-timeout: 30000
    connection-test-query: SELECT 1
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 600000
    destroy-method: shutdown
    auto-commit: false